version: '3.8'
services: 
  news-api:
    restart:
      always
    build: 
      context: ./
      dockerfile: Dockerfile
    depends_on:     
      - postgres
      - migrate
    links: 
      - postgres 
    ports: 
      - 9010:9010

  migrate:
    image: migrate/migrate
    depends_on:     
      - postgres
    volumes:
      - ./migrations:/migrations
    command: ["-path", "/migrations", "-database",  "postgres://pord:root@postgres:5432/news_api?sslmode=disable", "up"]
    links: 
      - postgres        

  postgres:
    restart: always
    image: postgres:14.5-alpine
    environment:
      POSTGRES_PASSWORD: root
    ports: 
      - 5432:5432
    volumes:
      - ./scripts/init_database.sql:/docker-entrypoint-initdb.d/1-init.sql